# Generated by Django 4.1.1 on 2022-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('blog', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(auto_now=True)),
            ],
        ),
    ]
