# Generated by Django 4.1.1 on 2022-10-04 17:55

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=blog.models.random_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
